[package]
name = "kasten-cli"
description = "The `kasten` command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "kasten"
path = "src/main.rs"

[dependencies]
kasten-core.workspace = true
serde_json.workspace = true

[lints]
workspace = true
