import type { Command } from "./types.ts";

/** View: zoom, the three views, panels, and presenting. */
export const viewCommands: Command[] = [
  {
    id: "view.zoom-in",
    label: "Zoom in",
    icon: "zoom-in",
    keys: ["Mod+=", "Mod+Plus"],
    scope: "global",
    run: ({ ui }) => ui.stepZoom(1),
  },
  {
    id: "view.zoom-out",
    label: "Zoom out",
    icon: "zoom-out",
    keys: ["Mod+-"],
    scope: "global",
    run: ({ ui }) => ui.stepZoom(-1),
  },
  {
    id: "view.zoom-fit",
    label: "Zoom to fit",
    icon: "maximize",
    keys: ["Mod+0"],
    scope: "global",
    run: ({ ui }) => ui.setZoom("fit"),
  },
  {
    id: "view.zoom-100",
    label: "100%",
    keys: ["Mod+1"],
    scope: "global",
    run: ({ ui }) => ui.setZoom(1),
  },
  {
    id: "view.edit",
    label: "Slide editor",
    icon: "rectangle-horizontal",
    checked: (_, ui) => ui.view === "edit",
    run: ({ ui }) => ui.setView("edit"),
  },
  {
    id: "view.outline",
    label: "Outline",
    icon: "list-tree",
    checked: (_, ui) => ui.view === "outline",
    run: ({ ui }) => ui.setView(ui.state.view === "outline" ? "edit" : "outline"),
  },
  {
    id: "view.grid",
    label: "Grid view",
    icon: "grid-2x2",
    checked: (_, ui) => ui.view === "grid",
    run: ({ ui }) => ui.setView(ui.state.view === "grid" ? "edit" : "grid"),
  },
  {
    id: "view.notes",
    label: "Speaker notes",
    icon: "notebook-pen",
    checked: (_, ui) => ui.notesOpen,
    run: ({ ui }) => ui.toggleNotes(),
  },
  {
    id: "view.filmstrip",
    label: "Filmstrip",
    icon: "panel-left",
    checked: (_, ui) => ui.filmstripOpen,
    run: ({ ui }) => ui.toggleFilmstrip(),
  },
  {
    id: "view.snap",
    label: "Snap to guides",
    icon: "ruler",
    checked: (_, ui) => ui.snap,
    run: ({ ui }) => ui.toggleSnap(),
  },
  {
    id: "view.full-screen",
    label: "Full screen",
    icon: "maximize",
    // F11 is a browser's own in some hosts.
    keys: ["Mod+Shift+F"],
    scope: "global",
    inFields: true,
    checked: (_, ui) => ui.fullScreen,
    run: ({ ui }) => ui.toggleFullScreen(),
  },
  {
    id: "view.format-panel",
    label: "Format options",
    icon: "panel-right",
    keys: ["Mod+Alt+O"],
    scope: "global",
    checked: (_, ui) => ui.panel === "format",
    run: ({ ui }) => ui.togglePanel("format"),
  },
  {
    id: "view.steps-panel",
    label: "Steps",
    icon: "list",
    checked: (_, ui) => ui.panel === "steps",
    run: ({ ui }) => ui.togglePanel("steps"),
  },
  {
    id: "view.ai-panel",
    label: "Assistant",
    icon: "sparkles",
    checked: (_, ui) => ui.panel === "ai",
    run: ({ ui }) => ui.togglePanel("ai"),
  },
  {
    id: "view.present",
    label: "Present",
    icon: "play",
    keys: ["Mod+Enter"],
    scope: "global",
    run: ({ ui }) => ui.actions.present?.("current"),
  },
  {
    id: "view.present-start",
    label: "Present from beginning",
    icon: "monitor-play",
    keys: ["Mod+Shift+Enter"],
    scope: "global",
    run: ({ ui }) => ui.actions.present?.("start"),
  },
  {
    id: "help.shortcuts",
    label: "Keyboard shortcuts",
    icon: "keyboard",
    keys: ["Mod+/"],
    scope: "global",
    run: ({ ui }) => ui.openDialog("shortcuts"),
  },
];
