//! The words of the four languages the lexer knows, and the names they go by.

use super::Spec;

pub(super) const TS: Spec = Spec {
    soft: &[
        "abstract",
        "as",
        "declare",
        "from",
        "get",
        "infer",
        "is",
        "keyof",
        "module",
        "namespace",
        "of",
        "override",
        "readonly",
        "satisfies",
        "set",
        "type",
    ],
    keywords: &[
        "abstract",
        "as",
        "async",
        "await",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "declare",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "finally",
        "for",
        "from",
        "function",
        "get",
        "if",
        "implements",
        "import",
        "in",
        "infer",
        "instanceof",
        "interface",
        "is",
        "keyof",
        "let",
        "namespace",
        "new",
        "of",
        "override",
        "private",
        "protected",
        "public",
        "readonly",
        "return",
        "satisfies",
        "set",
        "static",
        "switch",
        "throw",
        "try",
        "type",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        "yield",
    ],
    types: &[
        "string", "number", "boolean", "any", "unknown", "never", "object", "symbol", "bigint",
    ],
    constants: &[
        "true",
        "false",
        "null",
        "undefined",
        "NaN",
        "Infinity",
        "this",
        "super",
    ],
    line_comment: "//",
    block_comment: true,
    single_quotes: true,
    backticks: true,
    triple_quotes: false,
    annotations: true,
    toml: false,
};

pub(super) const KOTLIN: Spec = Spec {
    soft: &["by", "get", "out", "set", "value"],
    keywords: &[
        "abstract",
        "annotation",
        "as",
        "break",
        "by",
        "catch",
        "class",
        "companion",
        "const",
        "constructor",
        "continue",
        "crossinline",
        "data",
        "do",
        "else",
        "enum",
        "expect",
        "external",
        "final",
        "finally",
        "for",
        "fun",
        "get",
        "if",
        "import",
        "in",
        "infix",
        "init",
        "inline",
        "inner",
        "interface",
        "internal",
        "is",
        "lateinit",
        "noinline",
        "object",
        "open",
        "operator",
        "out",
        "override",
        "package",
        "private",
        "protected",
        "public",
        "reified",
        "return",
        "sealed",
        "set",
        "suspend",
        "tailrec",
        "throw",
        "try",
        "typealias",
        "val",
        "var",
        "vararg",
        "when",
        "where",
        "while",
    ],
    types: &[],
    constants: &["true", "false", "null", "this", "super", "it"],
    line_comment: "//",
    block_comment: true,
    single_quotes: true,
    backticks: false,
    triple_quotes: true,
    annotations: true,
    toml: false,
};

pub(super) const SWIFT: Spec = Spec {
    soft: &[],
    keywords: &[
        "actor",
        "as",
        "associatedtype",
        "async",
        "await",
        "break",
        "case",
        "catch",
        "class",
        "continue",
        "default",
        "defer",
        "deinit",
        "do",
        "else",
        "enum",
        "extension",
        "fallthrough",
        "fileprivate",
        "for",
        "func",
        "guard",
        "if",
        "import",
        "in",
        "init",
        "inout",
        "internal",
        "is",
        "lazy",
        "let",
        "open",
        "operator",
        "override",
        "private",
        "protocol",
        "public",
        "repeat",
        "rethrows",
        "return",
        "static",
        "struct",
        "subscript",
        "switch",
        "throw",
        "throws",
        "try",
        "typealias",
        "var",
        "where",
        "while",
    ],
    types: &[],
    constants: &["true", "false", "nil", "self", "super"],
    line_comment: "//",
    block_comment: true,
    single_quotes: false,
    backticks: false,
    triple_quotes: true,
    annotations: true,
    toml: false,
};

pub(super) const TOML: Spec = Spec {
    soft: &[],
    keywords: &[],
    types: &[],
    constants: &["true", "false", "inf", "nan"],
    line_comment: "#",
    block_comment: false,
    single_quotes: true,
    backticks: false,
    triple_quotes: true,
    annotations: false,
    toml: true,
};

/// The lexer for a language name or extension, if it is one of the four.
pub fn spec_for(name: &str) -> Option<&'static Spec> {
    match name {
        "typescript" | "ts" | "tsx" | "mts" | "cts" => Some(&TS),
        "kotlin" | "kt" | "kts" => Some(&KOTLIN),
        "swift" => Some(&SWIFT),
        "toml" => Some(&TOML),
        _ => None,
    }
}
